apiVersion: v1
kind: Service
metadata:
  name: open5gs-hss-svc-pool
  namespace: {{ .Values.namespace }}
  labels:
    epc-mode: hss
spec:
  ports:
  - name: s6a
    port: 3868
    protocol: TCP
  selector:
    epc-mode: hss
