apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.hss.fullname }}
  namespace: {{ .Values.namespace }}
  labels:
    epc-mode: hss
data:
  hss.yaml: |
    db_uri: {{ .Values.hss.db_uri }}
    
    logger:
        file: {{ .Values.hss.logger_file }}
    
    parameter:
    
    hss:
        freeDiameter: {{ .Values.hss.freediameter}}