kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: system:serviceaccount:open5g:mongo
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: pod-service-endpoint-reader
subjects:
  - kind: ServiceAccount
    name: mongo
    namespace: {{ .Values.namespace }}
