apiVersion: v1
kind: Service
metadata:
  name: open5gs-pcrf-svc-pool
  namespace: {{ .Values.namespace }}
  labels:
    epc-mode: pcrf
spec:
  ports:
  - name: gx
    port: 3868
    protocol: TCP
  selector:
    epc-mode: pcrf
