apiVersion: v1
kind: Service
metadata:
  name: open5gs-webui
  namespace: {{ .Values.namespace }}
  labels:
    epc-mode: webui
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 3000
  selector:
    epc-mode: webui
