apiVersion: v1
kind: Service
metadata:
  name: open5gs-pgw-svc-pool
  namespace: open5gs
  labels:
    epc-mode: pgw
spec:
  type: ClusterIP
  ports:
  - name: gtpc
    port: 2123
    protocol: UDP
  - name: gtpu
    port: 2152
    protocol: UDP  
  - name: gx
    port: 3868
    protocol: TCP      
  selector:
    epc-mode: pgw
